{
  "openapi" : "3.0.0",
  "info" : {
    "title" : "Scheduler",
    "description" : "The Scheduler APIs let you programmatically interact with [Zoom Scheduler](https://developers.zoom.us/docs/zoom-scheduler/) features. They allow you to schedule, manage, and retrieve details about meetings, webinars, and other events on the Zoom platform. With powerful tools for integration, these APIs streamline event management and automate workflows in external applications.",
    "termsOfService" : "https://zoom.us/docs/en-us/zoom_api_license_and_tou.html",
    "contact" : {
      "name" : "Zoom Developers",
      "url" : "https://developer.zoom.us/"
    },
    "version" : "2"
  },
  "servers" : [ {
    "url" : "https://api.zoom.us/v2"
  } ],
  "paths" : {
    "/scheduler/analytics" : {
      "get" : {
        "tags" : [ "analytics" ],
        "summary" : "Report analytics",
        "description" : "Generates the scheduler analytics report.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read`,`scheduler:read:admin`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:analytics`,`scheduler:read:analytics:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "report_analytics",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read", "scheduler:read:admin", "scheduler:read:analytics", "scheduler:read:analytics:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read", "scheduler:read:admin" ],
          "x-granular-scopes" : [ "scheduler:read:analytics", "scheduler:read:analytics:admin" ]
        }
      }
    },
    "/scheduler/availability" : {
      "get" : {
        "tags" : [ "availability" ],
        "summary" : "List availability",
        "description" : "Returns the availability schedules of the given user.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:list_availability`,`scheduler:read:list_availability:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "list_availability",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:list_availability", "scheduler:read:list_availability:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:list_availability", "scheduler:read:list_availability:admin" ]
        }
      },
      "post" : {
        "tags" : [ "availability" ],
        "summary" : "Insert availability",
        "description" : "Inserts a user availability schedule. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:availability`,`scheduler:write:availability:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "insert_availability",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:write:availability", "scheduler:write:availability:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:write:availability", "scheduler:write:availability:admin" ]
        }
      }
    },
    "/scheduler/availability/{availabilityId}" : {
      "get" : {
        "tags" : [ "availability" ],
        "summary" : "Get availability ",
        "description" : "Returns the availability schedule of the given UUID.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:availability`,`scheduler:read:availability:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "get_availability",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:availability", "scheduler:read:availability:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:availability", "scheduler:read:availability:admin" ]
        }
      },
      "delete" : {
        "tags" : [ "availability" ],
        "summary" : "Delete availability",
        "description" : "Removes a user's availability.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:delete:availability`,`scheduler:delete:availability:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "delete_availability",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:delete:availability", "scheduler:delete:availability:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:delete:availability", "scheduler:delete:availability:admin" ]
        }
      },
      "patch" : {
        "tags" : [ "availability" ],
        "summary" : "Patch availability",
        "description" : "Adjusts the availability schedule content of the given UUID.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:update:availability`,`scheduler:update:availability:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "patch_availability",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:update:availability", "scheduler:update:availability:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:update:availability", "scheduler:update:availability:admin" ]
        }
      }
    },
    "/scheduler/events" : {
      "get" : {
        "tags" : [ "scheduled events" ],
        "summary" : "List scheduled events",
        "description" : "Returns a list of all scheduled events.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:list_scheduled_events`,`scheduler:read:list_scheduled_events:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "list_scheduled_events",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:list_scheduled_events", "scheduler:read:list_scheduled_events:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:list_scheduled_events", "scheduler:read:list_scheduled_events:admin" ]
        }
      }
    },
    "/scheduler/events/{eventId}" : {
      "get" : {
        "tags" : [ "scheduled events" ],
        "summary" : "Get scheduled events ",
        "description" : "Returns a scheduled event.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:scheduled_event`,`scheduler:read:scheduled_event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "get_scheduled_events",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:scheduled_event", "scheduler:read:scheduled_event:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:scheduled_event", "scheduler:read:scheduled_event:admin" ]
        }
      },
      "delete" : {
        "tags" : [ "scheduled events" ],
        "summary" : "Delete scheduled events ",
        "description" : "Deletes a scheduled event.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:delete:scheduled_event`,`scheduler:delete:scheduled_event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "delete_scheduled_events",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:delete:scheduled_event", "scheduler:delete:scheduled_event:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:delete:scheduled_event", "scheduler:delete:scheduled_event:admin" ]
        }
      },
      "patch" : {
        "tags" : [ "scheduled events" ],
        "summary" : "Patch scheduled events",
        "description" : "Patches a scheduled event.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:update:scheduled_event`,`scheduler:update:scheduled_event:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "patch_scheduled_events",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:update:scheduled_event", "scheduler:update:scheduled_event:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:update:scheduled_event", "scheduler:update:scheduled_event:admin" ]
        }
      }
    },
    "/scheduler/schedules" : {
      "get" : {
        "tags" : [ "schedules" ],
        "summary" : "List schedules",
        "description" : "Returns a list of all schedules.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:list_schedule`,`scheduler:read:list_schedule:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "list_schedules",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:list_schedule", "scheduler:read:list_schedule:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:list_schedule", "scheduler:read:list_schedule:admin" ]
        }
      },
      "post" : {
        "tags" : [ "schedules" ],
        "summary" : "Insert schedules",
        "description" : "Creates a schedule.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:insert_schedule`,`scheduler:write:insert_schedule:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "insert_schedule",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:write:insert_schedule", "scheduler:write:insert_schedule:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:write:insert_schedule", "scheduler:write:insert_schedule:admin" ]
        }
      }
    },
    "/scheduler/schedules/{scheduleId}" : {
      "get" : {
        "tags" : [ "schedules" ],
        "summary" : "Get schedules",
        "description" : "Returns a schedule.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:get_schedule`,`scheduler:read:get_schedule:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "get_schedule",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:get_schedule", "scheduler:read:get_schedule:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:get_schedule", "scheduler:read:get_schedule:admin" ]
        }
      },
      "delete" : {
        "tags" : [ "schedules" ],
        "summary" : "Delete schedules",
        "description" : "Deletes a schedule.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:delete:delete_schedule`,`scheduler:delete:delete_schedule:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "delete_schedules",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:delete:delete_schedule", "scheduler:delete:delete_schedule:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:delete:delete_schedule", "scheduler:delete:delete_schedule:admin" ]
        }
      },
      "patch" : {
        "tags" : [ "schedules" ],
        "summary" : "Patch schedules",
        "description" : "Patches a schedule. \n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:update:patch_schedule`,`scheduler:update:patch_schedule:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "patch_schedule",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:update:patch_schedule", "scheduler:update:patch_schedule:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:update:patch_schedule", "scheduler:update:patch_schedule:admin" ]
        }
      }
    },
    "/scheduler/schedules/single_use_link" : {
      "post" : {
        "tags" : [ "scheduling links" ],
        "summary" : "Single use link",
        "description" : "Creates a single-use scheduling link.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:admin`,`scheduler:write`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:write:single_use_link`,`scheduler:write:single_use_link:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "single_use_link",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:write:admin", "scheduler:write", "scheduler:write:single_use_link", "scheduler:write:single_use_link:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:write:admin", "scheduler:write" ],
          "x-granular-scopes" : [ "scheduler:write:single_use_link", "scheduler:write:single_use_link:admin" ]
        }
      }
    },
    "/scheduler/users/{userId}" : {
      "get" : {
        "tags" : [ "users" ],
        "summary" : "Get user",
        "description" : "Returns information about the user.\n\n**[Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:admin`,`scheduler:read`\n\n**[Granular Scopes](https://developers.zoom.us/docs/integrations/oauth-scopes-overview/):** `scheduler:read:user`,`scheduler:read:user:admin`\n\n**[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `LIGHT`",
        "operationId" : "get_user",
        "security" : [ {
          "openapi_oauth" : [ "scheduler:read:admin", "scheduler:read", "scheduler:read:user", "scheduler:read:user:admin" ],
          "openapi_authorization" : [ ]
        } ],
        "x-extensions" : {
          "x-permissions" : [ ],
          "x-macro-scopes" : [ "scheduler:read:admin", "scheduler:read" ],
          "x-granular-scopes" : [ "scheduler:read:user", "scheduler:read:user:admin" ]
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "openapi_authorization" : {
        "type" : "apiKey",
        "name" : "Authorization",
        "in" : "header"
      },
      "openapi_oauth" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "/",
            "tokenUrl" : "",
            "refreshUrl" : "",
            "scopes" : {
              "scheduler:read" : "scheduler:read",
              "scheduler:read:admin" : "scheduler:read:admin",
              "scheduler:read:analytics" : "scheduler:read:analytics",
              "scheduler:read:analytics:admin" : "scheduler:read:analytics:admin",
              "scheduler:read:list_availability" : "scheduler:read:list_availability",
              "scheduler:read:list_availability:admin" : "scheduler:read:list_availability:admin",
              "scheduler:write:admin" : "scheduler:write:admin",
              "scheduler:write" : "scheduler:write",
              "scheduler:write:availability" : "scheduler:write:availability",
              "scheduler:write:availability:admin" : "scheduler:write:availability:admin",
              "scheduler:read:availability" : "scheduler:read:availability",
              "scheduler:read:availability:admin" : "scheduler:read:availability:admin",
              "scheduler:update:availability" : "scheduler:update:availability",
              "scheduler:update:availability:admin" : "scheduler:update:availability:admin",
              "scheduler:delete:availability" : "scheduler:delete:availability",
              "scheduler:delete:availability:admin" : "scheduler:delete:availability:admin",
              "scheduler:read:list_scheduled_events" : "scheduler:read:list_scheduled_events",
              "scheduler:read:list_scheduled_events:admin" : "scheduler:read:list_scheduled_events:admin",
              "scheduler:read:scheduled_event" : "scheduler:read:scheduled_event",
              "scheduler:read:scheduled_event:admin" : "scheduler:read:scheduled_event:admin",
              "scheduler:delete:scheduled_event" : "scheduler:delete:scheduled_event",
              "scheduler:delete:scheduled_event:admin" : "scheduler:delete:scheduled_event:admin",
              "scheduler:update:scheduled_event" : "scheduler:update:scheduled_event",
              "scheduler:update:scheduled_event:admin" : "scheduler:update:scheduled_event:admin",
              "scheduler:read:list_schedule" : "scheduler:read:list_schedule",
              "scheduler:read:list_schedule:admin" : "scheduler:read:list_schedule:admin",
              "scheduler:write:insert_schedule" : "scheduler:write:insert_schedule",
              "scheduler:write:insert_schedule:admin" : "scheduler:write:insert_schedule:admin",
              "scheduler:update:patch_schedule" : "scheduler:update:patch_schedule",
              "scheduler:update:patch_schedule:admin" : "scheduler:update:patch_schedule:admin",
              "scheduler:read:get_schedule" : "scheduler:read:get_schedule",
              "scheduler:read:get_schedule:admin" : "scheduler:read:get_schedule:admin",
              "scheduler:delete:delete_schedule" : "scheduler:delete:delete_schedule",
              "scheduler:delete:delete_schedule:admin" : "scheduler:delete:delete_schedule:admin",
              "scheduler:write:single_use_link" : "scheduler:write:single_use_link",
              "scheduler:write:single_use_link:admin" : "scheduler:write:single_use_link:admin",
              "scheduler:read:user" : "scheduler:read:user",
              "scheduler:read:user:admin" : "scheduler:read:user:admin"
            }
          }
        }
      }
    }
  }
}